### ISSUE TITLE
Using with @apply

### ISSUE THREAD

**Issue by wrabit** [benface/tailwindcss-gap#11]
Is there a trick here to be able to use with postcss + @apply?

`@apply flex c-gap c-gap-8`

**Comment by benface** [comment]
@wrabit Hmm, I'm not sure, since I don't use `@apply` much myself! I'm guessing if you created an issue it doesn't work haha. What's the error message? Have you tried with Tailwind's experimental `applyComplexClasses` option enabled?

```js
// tailwind.config.js
{
  experimental: {
    applyComplexClasses: true,
  },
}
```
