### ISSUE TITLE
Use core's `spacing` as default `gap`

### ISSUE THREAD

**Issue by hacknug** [benface/tailwindcss-gap#5]
Wanted to hear your thoughts on adding this. I always use those values and this change would at least save me 30 seconds every time I use your plugin.

Do you also use the same values most of the time? If not any reason not to I'm missing like I usually do? lol

**Comment by benface** [comment]
@hacknug Yeah, that seems reasonable! Will do it as part of the update that follows Tailwind v1.2 :)

**Comment by hacknug** [comment]
Perfect. Thanks @benface ❤️

**Comment by benface** [comment]
Done in the [`next` branch](https://github.com/benface/tailwindcss-gap/tree/next), which will be released as v4.0 when Tailwind v1.2 is released!
